function roi = rename_roi(roi, ROI_PREFIX)
    if matches(ROI_PREFIX, 'joanne')
        roi = replace(roi, ...
            ["ctx-rh-", "ctx-lh-", "Right", "Left", ...
             "BA46", "BA9", "BA6", "BA4", ...
             "precentral", "inferiorparietal", "superiorparietal", ...
             "insula", "caudalanteriorcingulate", "rostralanteriorcingulate", ...
             "FS.", "BA.", "-"], ...
            ["R ", "L ", "R", "L", ...
             "Middle Frontal Area (46)", ...
             "Granular Frontal Area (9)", ...
             "Supplementary Motor Area (6)", ...
             "Primary Motor Cortex (4)", ...
             "Precentral Gyrus", ...
             "Inferior Parietal Lobule", ...
             "Superior Parietal Lobule", ...
             "Insula", ...
             "Caudal Anterior Cingulate Cortex", ...
             "Rostral Anterior Cingulate Cortex", ...
             "", "", " "] ...
        );
    else
        roi = replace(roi, [ROI_PREFIX, '.'], ' ');
    end
end