clear; clc; close all;

rootDir = '/media/data3/Joanne_SRT_pw/'; 
batchFile = fullfile(rootDir, 'conn_out', 'v1_no_param.mat');
% batchFile = fullfile(rootDir, 'conn_out', 'v1_with_param.mat');

% COND_LIST = ["random", "structured", "switch"];
COND_LIST = ["random", "str_r12", "str_r34", "str_r56", "str_r78", "swi_r34", "swi_r56", "incorrect"];

%% First-level analysis 
% https://web.conn-toolbox.org/fmri-methods/connectivity-measures

conn_batch( ...
    'filename', batchFile, ...
    'Analysis.name', 'wSBC', ...
    'Analysis.measure', 1, ...     % correlation (bivariate)
    'Analysis.modulation', 0, ...  % standard weighted GLM analyses
    'Analysis.conditions', COND_LIST, ... 
    'Analysis.type', 3, ... 
    'Analysis.done', 1, ...
    'Analysis.overwrite', 'No' ...
)

conn_batch( ...
    'filename', batchFile, ...
    'Analysis.name', 'gPPI', ...
    'Analysis.measure', 3, ...     % regression (bivariate)
    'Analysis.modulation', 1, ...  % gPPI interaction effect
    'Analysis.conditions', COND_LIST, ... 
    'Analysis.type', 3, ...        % ROI-to-ROI & Seed-to-Voxel
    'Analysis.done', 1, ...
    'Analysis.overwrite', 'No' ...
)

    % 'Analysis.sources', {'atlas'}, ...

%% For the testing run

% batchFile = fullfile(rootDir, 'derivatives', 'CONN', 'mini_no_param.mat');
% COND_LIST = ["random", "structured"];
