clear; clc; close all;

rootDir = '/media/data3/Joanne_SRT_pw/'; 
batchFile = fullfile(rootDir, 'conn_out', 'v1_no_param.mat');
% batchFile = fullfile(rootDir, 'conn_out', 'v1_with_param.mat');

%% Second-level analysis 

conn_batch( ...
    'filename', batchFile, ...
    'Results.saveas', 'Str_Ran_r12', ...
    'Results.name', 'gPPI', ...
    'Results.between_subjects.effect_names', {'AllSubjects'}, ...
    'Results.between_subjects.contrast', [1], ...
    'Results.between_conditions.effect_names', {'str_r12', 'random'}, ...
    'Results.between_conditions.contrast', [1 -1], ...
    'Results.done', 1 ...
)

conn_batch( ...
    'filename', batchFile, ...
    'Results.saveas', 'Str_Ran_r34', ...
    'Results.name', 'gPPI', ...
    'Results.between_subjects.effect_names', {'AllSubjects'}, ...
    'Results.between_subjects.contrast', [1], ...
    'Results.between_conditions.effect_names', {'str_r34', 'random'}, ...
    'Results.between_conditions.contrast', [1 -1], ...
    'Results.done', 1 ...
)

conn_batch( ...
    'filename', batchFile, ...
    'Results.saveas', 'Str_Ran_r56', ...
    'Results.name', 'gPPI', ...
    'Results.between_subjects.effect_names', {'AllSubjects'}, ...
    'Results.between_subjects.contrast', [1], ...
    'Results.between_conditions.effect_names', {'str_r56', 'random'}, ...
    'Results.between_conditions.contrast', [1 -1], ...
    'Results.done', 1 ...
)

conn_batch( ...
    'filename', batchFile, ...
    'Results.saveas', 'Str_Ran_r78', ...
    'Results.name', 'gPPI', ...
    'Results.between_subjects.effect_names', {'AllSubjects'}, ...
    'Results.between_subjects.contrast', [1], ...
    'Results.between_conditions.effect_names', {'str_r78', 'random'}, ...
    'Results.between_conditions.contrast', [1 -1], ...
    'Results.done', 1 ...
)

conn_batch( ...
    'filename', batchFile, ...
    'Results.saveas', 'Swi_Ran_r34', ...
    'Results.name ', 'gPPI', ...
    'Results.between_subjects.effect_names', {'AllSubjects'}, ...
    'Results.between_subjects.contrast', [1], ...
    'Results.between_conditions.effect_names', {'swi_r34', 'random'}, ...
    'Results.between_conditions.contrast', [1 -1], ...
    'Results.done', 1 ...
)

conn_batch( ...
    'filename', batchFile, ...
    'Results.saveas', 'Swi_Ran_r56', ...
    'Results.name ', 'gPPI', ...
    'Results.between_subjects.effect_names', {'AllSubjects'}, ...
    'Results.between_subjects.contrast', [1], ...
    'Results.between_conditions.effect_names', {'swi_r56', 'random'}, ...
    'Results.between_conditions.contrast', [1 -1], ...
    'Results.done', 1 ...
)

%% GLM group-level analyses 
% https://web.conn-toolbox.org/resources/conn-extensions/glm

%% Launches conn gui to explore results

% conn
% conn('load', batchFile);
% conn gui_results